name: Teacups
version: '${project.version}'
main: io.github.berehum.teacups.TeacupsMain
api-version: 1.13
depend:
  - ProtocolLib
authors: [ Berehum ]
description: An extensive plugin that adds teacups to your minecraft server.