name: Bug Report
description: Report issues/unexpected behaviour
labels: [ 'bug', 'needs investigating' ]
assignees: [ 'Berehum' ]
body:
  - type: markdown
    attributes:
      value: |
        Before reporting an issue, please make sure you are using the latest version and if there isn't already an issue opned for this problem.
  - type: textarea
    attributes:
      label: Environment
      description: |
        Your server version (For instance: git-Paper-353 (MC: 1.17.1). Just put the output of /version here.)
        The version of Teacups that you're using. (Just put the output of /version Teacups here)
        The version of ProtocolLib that you're using. (Just put the output of /version ProtocolLib here)
      value: |
        - Server version:
        - TeacupsPro version:
        - ProtocolLib version:
  - type: textarea
    attributes:
      label: Description of Bug
      description: Describe what went wrong, and what the expected behaviour was.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Describe any steps or details intructions to reproduce this bug.
        Your answer may include any screenshots or videos, or may list steps.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I am running the latest version of TeacupsPro
          required: true
        - label: I am certain this issue is unique and a similar issue is not currently open
          required: true
  - type: textarea
    attributes:
      label: (OPTIONAL) Other
      description: |
        Please include other helpful information below.
        This field is not required.
    validations:
      required: false