name: Documentation
description: Suggest changes to the documentation/wiki
labels: [ 'documentation', 'needs investigating' ]
assignees: [ 'Berehum' ]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type of Change
      multiple: false
      options:
        - Fix typo
        - Clarify ambigious information
        - Add new information
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of Change
      description: |
        Describe the change in full.
    validations:
      required: true
  - type: textarea
    attributes:
      label: (OPTIONAL) Page Markup
      description: |
        If you are describing an edit, it would be helpful if you posted the revised markup for the **whole** page here. Please see the wiki for instructions on how to do this.
        This field is not required.
      render: true
    validations:
      required: false
