name: CustomEntity
version: '${project.version}'
main: io.github.berehum.customentity.CustomEntityMain
api-version: 1.13
authors: [ Berehum ]
description: Experimenting with custom entities using NMS.

commands:
  spawnalpha:
    description: Spawns an alpha wolf with its pack.
